### ISSUE TITLE
Prompt token consumption grows until /reset

### ISSUE THREAD

**Issue by k3it** [n3d1117/chatgpt-telegram-bot#34] opened 2023-03-03 16:41 UTC
Hi.
Thank you for the updates and support of the turbo model!

I noticed that each subsequent query within a conversation uses up more prompt tokens. this continues until I reset the session.  Does this sound like the correct behavior?

here is an example of the same prompt, with each iteration increasing token usage:

![image](https://user-images.githubusercontent.com/9923389/222776926-84217238-9670-4357-96a8-dbcf90965ed0.png)

**Comment by n3d1117** [comment] 2023-03-03 17:08
Hi @k3it, good catch. Yeah, I think it's showing the sum of the prompt tokens used within a conversation.

I would say that's the expected behavior, since I'm not doing any calculations myself, just printing the `usage` object that is returned by the API. Anyway I will keep this issue open in case anyone has more knowledge on this!

**Comment by k3it** [comment] 2023-03-03 18:20
I did some more checking and it looks like "Token used" is an individual counter for each prompt/response transaction.  it is not a cumulative for the current conversation.   So each new question within the same conversation becomes exponentially more expensive to ask.   

After a long session without a /reset it may be cheaper to buy and weight the banana yourself instead of asking the bot about it :)

**Comment by n3d1117** [comment] 2023-03-04 12:19
Indeed it looks like sending history also cosumes tokens.

Here's what [the docs](https://platform.openai.com/docs/guides/chat/introduction) say:

> Including the conversation history helps when user instructions refer to prior messages. [...] Because the models have no memory of past requests, all relevant information must be supplied via the conversation. If a conversation cannot fit within the model’s token limit, it will need to be shortened in some way.

So I agree that history needs to be truncated or summarized somehow. I commented on your [PR](https://github.com/n3d1117/chatgpt-telegram-bot/pull/35)

**Comment by n3d1117** [comment] 2023-03-05 20:27
@k3it Should be fixed in 946f6a4. Feel free to reopen if issue persists

**Closed by n3d1117** 2023-03-05 20:27 UTC

**Comment by em108** [comment] 2023-03-06 17:32
Hello and thanks a lot for the updates and fixes
I've seen this application of embeddings in another bot (link below) to solve the token issue. Would it be a good idea to implement to further reduce on the token consumption?

https://github.com/LagPixelLOL/ChatGPTCLIBot

**Comment by n3d1117** [comment] 2023-03-06 21:11
Hi @em108 I'm not familiar with embeddings or how they can be implemented in python. What are the advantages?

**Comment by em108** [comment] 2023-03-06 21:36
From what I've gathered from multiple sources including the article below, embeddings can aid in long term memory / a way to store conversation data. Based on the cost and application, they can cost up to 5 - ~9 times less than sending chat history.

Article:
https://towardsdatascience.com/generative-question-answering-with-long-term-memory-c280e237b144


Also an example of a notebook utilizing embeddings: 
https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb

**Comment by n3d1117** [comment] 2023-03-07 09:06
Very interesting, thanks @em108. Would be great, although I currently don't have the time to implement this
