### ISSUE TITLE
On audio message: AttributeError: 'async_generator' object has no attribute 'choices'

### ISSUE THREAD

**Issue by nielsole** [n3d1117/chatgpt-telegram-bot#117] opened 2023-03-26 17:54 UTC
```
          - name: MONTHLY_USER_BUDGETS
            value: "20"
          - name: VOICE_REPLY_WITH_TRANSCRIPT_ONLY
            value: "false"
          - name: TEMPERATURE
            value: "0.7"
```
```
2023-03-26 17:49:45,936 - root - INFO - New transcribe request received from user Niels-Ole
2023-03-26 17:49:47,024 - openai - INFO - message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=549 request_id=XXXXXXXXXXXXXXXXXXXX response_code=200
2023-03-26 17:49:47,888 - openai - INFO - message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=394 request_id=XXXXXXXXXXXXXXXXXXXX response_code=200
2023-03-26 17:49:47,893 - root - ERROR - 'async_generator' object has no attribute 'choices'
Traceback (most recent call last):
  File "/app/bot/telegram_bot.py", line 259, in transcribe
    response, total_tokens = await self.openai.get_chat_response(chat_id=chat_id, query=transcript)
  File "/app/bot/openai_helper.py", line 55, in get_chat_response
    if len(response.choices) > 1 and self.config['n_choices'] > 1:
AttributeError: 'async_generator' object has no attribute 'choices'
```

**Comment by n3d1117** [comment] 2023-03-26 22:42
Hi @nielsole, this is a duplicate of #114 and should already be fixed in `main` branch

**Closed by n3d1117** 2023-03-26 22:42 UTC

**Comment by nielsole** [comment] 2023-03-27 13:46
sorry for not catching the duplicate. Thanks for  this great software!
