### ISSUE TITLE
root - ERROR - Exception while handling an update: 'total_usage'

### ISSUE THREAD

**Issue by Happyigr** [n3d1117/chatgpt-telegram-bot#390] opened 2023-07-27 18:13 UTC
I discovered this error from the moment I uploaded this script to my server, after which this error started appearing on both my main PC and the server. What can I do to fix it?

**Comment by n3d1117** [comment] 2023-07-28 19:35
Closing as duplicate of #385

**Closed by n3d1117** 2023-07-28 19:35 UTC
