### ISSUE TITLE
The result from summarisation is not always reliable. 

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#53] opened 2023-03-13 09:30 UTC
could you set it up such that if the total token exceeds the max, delete half of the chat history? This way, you can prevent excessive use of tokens while still retaining some chat history for better context.

**Comment by mithew** [comment] 2023-03-13 17:28
or keep the oldest and latest four messages when the chat history exceeds 15, and delete the rest.

**Comment by n3d1117** [comment] 2023-03-14 12:07
Hi @mithew, what's not reliable about summarisation? Can you provide an example?

**Comment by mithew** [comment] 2023-03-14 12:15
> Hi @mithew, what's not reliable about summarisation? Can you provide an example?

If the number of tokens exceeds the set limit during chat, the program should summarize and streamline some old chat records to ensure smooth conversation. However, I still frequently encounter a 4096 error during use, indicating that the summarization function is ineffective.

**Comment by n3d1117** [comment] 2023-03-14 13:25
Yes, so this is a duplicate of #45

**Closed by n3d1117** 2023-03-14 13:25 UTC
