### ISSUE TITLE
Bot fails to connect: ConnectionRefusedError and NetworkError

### ISSUE THREAD

**Issue by immelnet-code** [n3d1117/chatgpt-telegram-bot#97] opened 2023-03-22 10:01 UTC
I encountered an issue when trying to run the ChatGPT Telegram bot. The bot fails to connect and raises a `ConnectionRefusedError` and `NetworkError`.

**Error message and traceback:**
(venv) root@vultr:~/dev/chatgpt-telegram-bot# python3 bot/main.py
/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('::1', 8080, 0, 0)
----------------------------
Traceback (most recent call last):
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_async/http_proxy.py", line 261, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 199, in do_request
    res = await self._client.request(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/dev/chatgpt-telegram-bot/bot/main.py", line 72, in <module>
    main()
  File "/root/dev/chatgpt-telegram-bot/bot/main.py", line 68, in main
    telegram_bot.run()
  File "/root/dev/chatgpt-telegram-bot/bot/telegram_bot.py", line 500, in run
    application.run_polling()
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 724, in run_polling
    return self.__run(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 918, in __run
    raise exc
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 907, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 396, in initialize
    await self.bot.initialize()
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 252, in initialize
    await super().initialize()
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 544, in initialize
    await self.get_me()
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 1677, in get_me
    return await super().get_me(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 689, in get_me
    result = await self._post(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
  File "/root/dev/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 223, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed

**Steps to reproduce:**
1. Set up the environment and install dependencies.
2. Run the bot with `python3 bot/main.py`.

**Environment:**
- OS: Debian GNU/Linux 11 (bullseye)
- Python version: 3.10.10

**Comment by n3d1117** [comment] 2023-03-22 10:03
Hi @immelnet-code, can you share your `.env` file? (make sure to redact openai api key and telegram token)

**Comment by n3d1117** [comment] 2023-03-22 10:11
Just delete everything you don't need from the `.env` file (especially the proxy line, which should default to none)

Duplicate of #81. Readme will be made clearer soon

**Closed by n3d1117** 2023-03-22 10:11 UTC
