### ISSUE TITLE
Hope to add HTTP proxy

### ISSUE THREAD

**Issue by xmbhjQAQ** [n3d1117/chatgpt-telegram-bot#10] opened 2022-12-08 06:02 UTC
In some application environments, I can only connect to telegram and openai through proxy. This means that I need to open the global proxy, which will affect the running of other programs. I tried to add

{os.environ["http_proxy"] = " http://127.0.0.1:1231 "} But it doesn't seem to work?

**Comment by n3d1117** [comment] 2022-12-08 10:28
Hi, in https://github.com/n3d1117/chatgpt-telegram-bot/commit/da781320e46812a10fce132b287a41940a725bb5 I added support for specifying proxy as optional configuration.

1. In your `.env` file add the following:
```bash
PROXY='http://localhost:8080' # or whatever is your proxy
```
2. Done! It should be automatically picked up by the `revChatGpt` package

I don't have a proxy so kindly let me know if it works for you!

**Comment by xmbhjQAQ** [comment] 2022-12-08 10:32
THK for your reply.Im glad to hear the meassage..One more question..Is it support Socks5?

**Comment by n3d1117** [comment] 2022-12-08 10:48
> One more question..Is it support Socks5?

Authentication is handled by [acheong08/OpenAIAuth](https://github.com/acheong08/OpenAIAuth), so you should open an issue there!
I'm going to close this as completed, feel free to reopen if you have any more issues

**Closed by n3d1117** 2022-12-08 10:48 UTC

**Comment by xmbhjQAQ** [comment] 2022-12-10 08:24
I just tried to add an HTTP proxy, but it doesn't seem to work. I also did not find his traffic in my server

**Comment by n3d1117** [comment] 2022-12-10 11:55
> I just tried to add an HTTP proxy, but it doesn't seem to work. I also did not find his traffic in my server

Hi @xmbhjQAQ , can you try now using latest commit?

**Comment by n3d1117** [comment] 2022-12-10 13:20
Then the issue is with the library [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT), please open an issue there

**Comment by callmeeric5** [comment] 2023-03-27 09:18
> 

Hi, have you solved this yet? It seems like I meet the same as you.
With Proxy Config: telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
Without Proxy Config:  RuntimeWarning:  telegram.error.TimedOut: Timed out

Settings: global proxy in clashx
