### ISSUE TITLE
VOICE_REPLY_WITH_TRANSCRIPT_ONLY with FALSE

### ISSUE THREAD

**Issue by rome2rome** [n3d1117/chatgpt-telegram-bot#153] opened 2023-04-01 08:10 UTC
I used Docker Hub (0.2.1)  to deploy the ChatGPT Telegram bot. When I tried to set 'VOICE_REPLY_WITH_TRANSCRIPT_ONLY' to 'false', I encountered an error: 'Failed to transcribe text: 'async_generator' object has no attribute 'choices''. However, everything worked fine when I set 'VOICE_REPLY_WITH_TRANSCRIPT_ONLY' to 'true'."

It seems like the issue is related to setting 'VOICE_REPLY_WITH_TRANSCRIPT_ONLY' to 'false'. The error message 'async_generator' object has no attribute 'choices' indicates that there might be an issue with the code that's responsible for transcribing the voice input. It's possible that the code is trying to use the 'choices' method on an 'async_generator' object, which is not defined for that object type.

**Comment by n3d1117** [comment] 2023-04-01 08:17
Hi @rome2rome, did you just use chatgpt to explain the error? 😆 

Duplicate of #117, already fixed and will work with a new release

**Closed by n3d1117** 2023-04-01 08:17 UTC

**Comment by rome2rome** [comment] 2023-04-01 08:24
:) yes,  I used chatgpt. Thank you for your quick response.
